language: c
sudo: required
before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -q
install:
  - sudo apt-get install gcc-arm-embedded
script:
  - make clean
  - make all