#define MYNEWT_VAL_BLE_MESH_MODEL_KEY_COUNT                             1
#define MYNEWT_VAL_BLE_MESH_MODEL_GROUP_COUNT                           2
#define MYNEWT_VAL_BLE_MESH_APP_KEY_COUNT                               2
#define MYNEWT_VAL_BLE_MESH_SUBNET_COUNT                                2
#define MYNEWT_VAL_BLE_MESH_CRPL                                        10
#define MYNEWT_VAL_BLE_MESH_MSG_CACHE_SIZE                              10
#define MYNEWT_VAL_BLE_MESH_ADV_BUF_COUNT                               20
#define MYNEWT_VAL_BLE_MESH_TX_SEG_MSG_COUNT                            1
#define MYNEWT_VAL_BLE_MESH_RX_SEG_MSG_COUNT                            1
#define MYNEWT_VAL_BLE_MESH_DEBUG_TRANS                                 1
#define MYNEWT_VAL_BLE_MESH_FRIEND                                      1
#define MYNEWT_VAL_BLE_MESH_LOW_POWER                                   0
#define MYNEWT_VAL_BLE_MESH_SETTINGS                                    0
#define MYNEWT_VAL_BLE_MESH_FRIEND_SUB_LIST_SIZE                        3
#define MYNEWT_VAL_BLE_MESH_FRIEND_SEG_RX                               1
#define MYNEWT_VAL_BLE_MESH_FRIEND_LPN_COUNT                            2
#define MYNEWT_VAL_BLE_MESH_DEBUG_BEACON                                0
#define MYNEWT_VAL_BLE_MESH_DEBUG_CRYPTO                                0
#define MYNEWT_VAL_BLE_MESH_PROV                                        1
#define MYNEWT_VAL_BLE_MESH_DEBUG_MODEL                                 0
#define MYNEWT_VAL_BLE_MESH_DEBUG_ADV                                   0
#define MYNEWT_VAL_BLE_MESH_DEBUG                                       0
#define MYNEWT_VAL_BLE_MESH_PB_GATT                                     1
#define MYNEWT_VAL_BLE_MESH_LABEL_COUN                                  3
#define MYNEWT_VAL_BLE_MESH_RELAY                                       1
#define MYNEWT_VAL_BLE_MESH_GATT_PROXY                                  1
#define MYNEWT_VAL_BLE_MESH_TESTING                                     0
#define MYNEWT_VAL_BLE_MESH_DEBUG_NET                                   0
#define MYNEWT_VAL_BLE_MESH_IV_UPDATE_TEST                              0
#define MYNEWT_VAL_BLE_MESH_IVU_DIVIDER                                 4
#define MYNEWT_VAL_BLE_MESH_DEBUG_PROV                                  0
#define MYNEWT_VAL_BLE_MESH_FRIEND_QUEUE_SIZE                           16
#define MYNEWT_VAL_BLE_MESH_DEBUG_FRIEND                                0
#define MYNEWT_VAL_BLE_MESH_FRIEND_RECV_WIN                             255
#define MYNEWT_VAL_BLE_SVC_DIS_MODEL_NUMBER_DEFAULT                     ""
#define MYNEWT_VAL_BLE_SVC_DIS_SERIAL_NUMBER_DEFAULT                    ""
#define MYNEWT_VAL_BLE_SVC_DIS_FIRMWARE_REVISION_DEFAULT                ""
#define MYNEWT_VAL_BLE_SVC_DIS_MANUFACTURER_NAME_DEFAULT                ""
#define MYNEWT_VAL_BLE_SVC_DIS_MODEL_NUMBER_READ_PERM                   0
#define MYNEWT_VAL_BLE_SVC_DIS_HARDWARE_REVISION_READ_PERM              0
#define MYNEWT_VAL_BLE_MESH_RX_SDU_MAX                                  384
#define MYNEWT_VAL_BLE_MESH_PB_ADV                                      1
#define MYNEWT_VAL_BLE_SVC_DIS_HARDWARE_REVISION_DEFAULT                ""
#define MYNEWT_VAL_BLE_SVC_DIS_SERIAL_NUMBER_READ_PERM                  0
#define MYNEWT_VAL_BLE_SVC_DIS_FIRMWARE_REVISION_READ_PER               0
#define MYNEWT_VAL_BLE_MESH_PROXY                                       1
#define MYNEWT_VAL_BLE_MESH_LABEL_COUNT                                 3
#define MYNEWT_VAL_BLE_MESH_DEBUG_ACCESS                                0
#define MYNEWT_VAL_BLE_MESH_PROXY_FILTER_SIZE                           3
#define MYNEWT_VAL_BLE_MESH_DEBUG_PROXY                                 0
#define MYNEWT_VAL_BLE_MESH_NODE_ID_TIMEOUT                             60
#define MYNEWT_VAL_BLE_MESH_DEVICE_NAME                                 ""
#define MYNEWT_VAL_BLE_SVC_DIS_SOFTWARE_REVISION_DEFAULT                ""
#define MYNEWT_VAL_BLE_SVC_DIS_FIRMWARE_REVISION_READ_PERM              0
#define MYNEWT_VAL_BLE_SVC_DIS_SOFTWARE_REVISION_READ_PERM              0
#define MYNEWT_VAL_BLE_SVC_DIS_MANUFACTURER_NAME_READ_PERM              0
